issue-3250: added workflow + updated versions
jdi-templates/jdi-dark-junit-template pull request #7
Opened 2021-08-27 11:46 UTC by n-ton4

2021-08-30 10:04 UTC, pnatashap requested changes

2021-08-30 10:04 UTC, pnatashap commented on .github/workflows/maven.yml
> +        if: github.event_name == 'pull_request' && failure()
а почему мы историю забираем только при ошибке? а загружаем в любом случае?

2021-08-30 10:04 UTC, pnatashap commented on .github/workflows/maven.yml
> +        run: mvn install -DskipTests
-ntp

2021-08-30 10:04 UTC, pnatashap commented on .github/workflows/maven.yml
> +        run: mvn test
-ntp

2021-09-01 18:21 UTC, n-ton4 commented on .github/workflows/maven.yml
> +        if: github.event_name == 'pull_request' && failure()
Когда истории много это достаточно дорогая операция. Я с этим сталкивался. Я бы вообще репорт не собирал, если билд зеленый.

2021-09-06 14:16 UTC, knadonenko approved these changes

2021-09-06 14:25 UTC, merged